############################################################
# Dockerfile to build cheebacoind container images
# Based on Ubuntu
############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-leveldb libboost-all-dev libssl-dev libdb++-dev pkg-config libminiupnpc-dev wget xz-utils
RUN apt-get clean

RUN adduser cheebacoin --disabled-password
USER cheebacoin

WORKDIR /home/cheebacoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/cheebacoin/src
RUN git clone https://github.com/cheebacoin-project/cheebacoin.git

WORKDIR	/home/cheebacoin/src/cheebacoin/src
RUN make -f makefile.unix
RUN strip cheebacoind
RUN cp -f cheebacoind /home/cheebacoin/bin/
RUN make -f makefile.unix clean

WORKDIR	 /home/cheebacoin
RUN mkdir .cheebacoin
RUN cp -f src/cheebacoin/contrib/docker/cheebacoin.conf .cheebacoin/

WORKDIR /home/cheebacoin/.cheebacoin
RUN wget -q https://github.com/cheebacoin-project/cheebacoin/releases/download/v1.3.1.2/bootstrap.dat.xz

ENV HOME /home/cheebacoin
EXPOSE 8332
USER cheebacoin
