###############################################################
# Dockerfile to build cheebacoin-electrum server container images
# Based on Ubuntu
###############################################################

FROM ubuntu:14.04
MAINTAINER laudney

RUN apt-get update
RUN apt-get install -y git make g++ python-setuptools python-openssl python-leveldb python-dev libleveldb-dev wget
RUN apt-get clean
RUN easy_install jsonrpclib irc plyvel

RUN adduser cheebacoin --disabled-password
USER cheebacoin

WORKDIR /home/cheebacoin
RUN mkdir bin src
RUN echo PATH=\"\$HOME/bin:\$PATH\" >> .bash_profile

WORKDIR /home/cheebacoin/src
RUN git clone https://github.com/cheebacoin-project/cheebacoin-electrum-server.git

USER root
WORKDIR /home/cheebacoin/src/cheebacoin-electrum-server
RUN ./configure
RUN python setup.py install

WORKDIR /var
RUN touch /var/log/electrum.log
RUN chown cheebacoin:cheebacoin /var/log/electrum.log
RUN wget -q http://reddwallet.org/electrum.tar.gz
RUN tar -zxvf electrum.tar.gz
RUN rm electrum.tar.gz
RUN chown cheebacoin:cheebacoin -R electrum-server

RUN echo "cheebacoin hard nofile 65536" >> /etc/security/limits.conf
RUN echo "cheebacoin soft nofile 65536" >> /etc/security/limits.conf

USER cheebacoin
WORKDIR	/home/cheebacoin
RUN openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
RUN openssl rsa -passin pass:x -in server.pass.key -out server.key
RUN rm server.pass.key
RUN openssl req -new -key server.key -out server.csr -subj '/CN=www.my.com/O=My Company Name LTD./C=US'
RUN openssl x509 -req -days 730 -in server.csr -signkey server.key -out server.crt

ENV HOME /root
EXPOSE 50001 50002
USER root
